##   
## github地址 https://github.com/chinnkarahoi/jd_scripts

## boxjs链接  


## 新建一个库，此文件路径为 .github/workflows/ziye-sync.yml 打开教程链接 https://www.jianshu.com/p/bb82b3ad1d11 ，申请PAT（勾选时尽量全部勾选 ），找到Settings------secrets------New repository secret------name填写PAT    value填写PAT的值        

## 点击 Actions  手动运行或者等待定时运行即可自动生成分支 ZIYE 且自动同步文件至此

## 其他作者库同理  替换如下    
 
## 作者名         chinnkarahoi  
## 作者库名       jd_scripts     
## 作者分支名     master     
## 同步分支名     LXK9031   （可自定义 ）




name: LXK9031-sync
on:
  schedule:
    - cron: '20 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-chinnkarahoi-jd_scripts
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync chinnkarahoi-jd_scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/chinnkarahoi/jd_scripts.git"
          source_branch: "master"
          destination_branch: "LXK9031"
          github_token: ${{ secrets.PAT }}
